apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl-ui-deployment
  labels:
    app: kubectl-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl-ui
  template:
    metadata:
      labels:
        app: kubectl-ui
    spec:
      serviceAccountName: kubectl-ui-sa
      containers:
      - name: kubectl-ui
        image: dmesa2/kubectl_ui:latest
        ports:
        - containerPort: 3000
